config/routes.rb
Odot::Application.routes.draw do

  namespace :api do
    resources :todo_lists do
      resources :todo_items, only: [:index, :create, :update, :destroy]
    end
  end

  resources :todo_lists do
    resources :todo_items do
      member do
        patch :complete
      end
    end
  end

  root 'todo_lists#index'

end

app/models/todo_item.rb
class TodoItem < ActiveRecord::Base
  belongs_to :todo_list

  validates :content, presence: true, length: { minimum: 2 }

  def completed?
    !completed_at.blank?
  end
end

app/models/todo_list.rb
class TodoList < ActiveRecord::Base
  has_many :todo_items

  validates :title, presence: true, length: { minimum: 3 }
  validates :description, presence: true, length: { minimum: 5 }
end

app/controllers/api/api_controller.rb
module Api
  class ApiController < ApplicationController
    skip_before_filter :verify_authenticity_token
    protect_from_forgery with: :null_session
    before_filter :authenticate

    def authenticate
      authenticate_or_request_with_http_basic do |user, password|
        user == "admin" && password == "secret"
      end
    end
  end
end

app/controllers/api/todo_items_controller.rb
class Api::TodoItemsController < Api::ApiController
  before_filter :find_todo_list

  def index
    render json: @list.todo_items
  end

  def create
    item = @list.todo_items.new(todo_item_params)
    if item.save
      render status: 200, json: {
        message: "Successfully created todo item",
        todo_list: @list,
        todo_item: item
      }.to_json
    else
      render status: 422, json: {
        message: "Todo item creation failed",
        errors: item.errors
      }.to_json
    end
  end

  def update
    item = @list.todo_items.find(params[:id])
    if item.update(todo_item_params)
      render status: 200, json: {
        message: "Successfully updated todo item",
        todo_list: @list,
        todo_item: item
      }.to_json
    else
      render status: 422, json: {
        message: "Todo item update failed",
        errors: item.errors
      }.to_json
    end
  end

  def destroy
    item = @list.todo_items.find(params[:id])
    item.destroy
    render status: 200, json: {
      message: "Successfully deleted todo item",
      todo_list: @list,
      todo_item: item
    }.to_json
  end

  private

  def todo_item_params
    params.require(:todo_item).permit(:content)
  end

  def find_todo_list
    @list = TodoList.find(params[:todo_list_id])
  end
end

app/controllers/api/todo_lists_controller.rb
class Api::TodoListsController < Api::ApiController

  def index
    render json: TodoList.all
  end

  def show
    list = TodoList.find(params[:id])
    render json: list.as_json(include: [:todo_items])
  end

  def create
    list = TodoList.new(todo_list_params)
    if list.save
      render status: 200, json: {
        message: "Successfully created todo list",
        todo_list: list
      }.to_json
    else
      render status: 422, json: {
        message: "Todo list creation failed",
        errors: list.errors
      }.to_json
    end
  end

  def update
    list = TodoList.find(params[:id])
    if list.update(todo_list_params)
      render status: 200, json: {
        message: "Successfully updated todo list",
        todo_list: list
      }.to_json
    else
      render status: 422, json: {
        message: "Todo list update failed",
        errors: list.errors
      }.to_json
    end
  end

  def destroy
    list = TodoList.find(params[:id])
    list.destroy
    render status: 200, json: {
      message: "Successfully deleted todo list"
    }.to_json
  end

  private

  def todo_list_params
    params.require(:todo_list).permit(:title, :description)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/todo_items_controller.rb
class TodoItemsController < ApplicationController
  before_action :find_todo_list
  before_action :set_todo_item, only: [:show, :edit, :update, :destroy, :complete]

  def index
  end

  def show
  end

  def new
    @todo_item = @todo_list.todo_items.new
  end

  def edit
  end

  def create
    @todo_item = @todo_list.todo_items.new(todo_item_params)
    if @todo_item.save
      flash[:success] = 'Added todo list item.'
      redirect_to todo_list_todo_items_path
    else
      flash[:error] = 'There was a problem adding that todo list item.'
      render action: :new
    end
  end

  def update
    if @todo_item.update(todo_item_params)
      flash[:success] = 'Updated todo list item.'
      redirect_to todo_list_todo_items_path
    else
      flash[:error] = 'That todo item could not be updated.'
      render action: :edit
    end
  end

  def destroy
    if @todo_item.destroy
      flash[:success] = 'Todo list item was deleted.'
    else
      flash[:error] = 'Todo list item could not be deleted.'
    end
    redirect_to todo_list_todo_items_path
  end

  def complete
    @todo_item.update_attribute(:completed_at, Time.now)
    redirect_to todo_list_todo_items_path, notice: 'Todo item marked as complete.'
  end

  private

    def find_todo_list
      @todo_list = TodoList.find(params[:todo_list_id])
    end

    def set_todo_item
      @todo_item = @todo_list.todo_items.find(params[:id])
    end

    def todo_item_params
      params[:todo_item].permit(:content)
    end
end

app/controllers/todo_lists_controller.rb
class TodoListsController < ApplicationController
  before_action :set_todo_list, only: [:show, :edit, :update, :destroy]

  # GET /todo_lists
  # GET /todo_lists.json
  def index
    @todo_lists = TodoList.all
  end

  # GET /todo_lists/1
  # GET /todo_lists/1.json
  def show
  end

  # GET /todo_lists/new
  def new
    @todo_list = TodoList.new
  end

  # GET /todo_lists/1/edit
  def edit
  end

  # POST /todo_lists
  # POST /todo_lists.json
  def create
    @todo_list = TodoList.new(todo_list_params)

    respond_to do |format|
      if @todo_list.save
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully created.' }
        format.json { render action: 'show', status: :created, location: @todo_list }
      else
        format.html { render action: 'new' }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todo_lists/1
  # PATCH/PUT /todo_lists/1.json
  def update
    respond_to do |format|
      if @todo_list.update(todo_list_params)
        format.html { redirect_to @todo_list, notice: 'Todo list was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todo_lists/1
  # DELETE /todo_lists/1.json
  def destroy
    @todo_list.destroy
    respond_to do |format|
      format.html { redirect_to todo_lists_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo_list
      @todo_list = TodoList.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def todo_list_params
      params.require(:todo_list).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todo_items_helper.rb
module TodoItemsHelper
end

app/helpers/todo_lists_helper.rb
module TodoListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Odot</title>
<%= stylesheet_link_tag "application", media: "all" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>
</head>

<body>

  <% flash.each do |type, message| %>
    <div class='alert flash <%= type %>'>
      <%= message %>
    </div>
  <% end %>

  <div>
    <h1>
      <%= link_to 'Odot', root_path %>
    </h1>
    <ul class="nav">
      <li>
        <%= link_to 'Todo Lists', todo_lists_path %>
      </li>
    </ul>
  </div>

  <%= yield %>

</body>
</html>

app/views/todo_items/_form.html.erb
<%= form_for [@todo_list, @todo_item] do |f| %>
  <% if @todo_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_item.errors.count, "error") %> prohibited this todo item from being saved:</h2>
      <ul>
      <% @todo_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= f.label :content %>
    <%= f.text_area :content %>
  </div>

  <div>
    <%= f.submit 'Save' %>
  </div>
<% end %>

app/views/todo_items/edit.html.erb
<h1>Editing todo_item</h1>

<%= render 'form' %>

app/views/todo_items/index.html.erb
<h2>
  <%= @todo_list.title %>
</h2>

<ul class='todo_items'>
  <% @todo_list.todo_items.each do |todo_item| %>
  <li id='<%= dom_id(todo_item) %>'>
    <% if todo_item.completed? %>
      <%= todo_item.completed_at %>
    <% else %>
      <%= link_to 'Mark complete', complete_todo_list_todo_item_path(@todo_list, todo_item.id), method: :patch %>
    <% end %>
    <%= todo_item.content %>
    <%= link_to 'Edit', edit_todo_list_todo_item_path(@todo_list, todo_item.id) %>
    <%= link_to 'Delete', todo_list_todo_item_path(@todo_list, todo_item.id),
      method: :delete, data: { confirm: 'Are you sure?'} %>
  </li>
  <% end %>
</ul>

<p>
  <%= link_to 'New Todo Item', new_todo_list_todo_item_path(@todo_list) %>
</p>

app/views/todo_items/new.html.erb
<h1>New todo item</h1>

<%= render 'form' %>

app/views/todo_lists/_form.html.erb
<%= form_for(@todo_list) do |f| %>
  <% if @todo_list.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@todo_list.errors.count, "error") %> prohibited this todo_list from being saved:</h2>
      <ul>
      <% @todo_list.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/todo_lists/edit.html.erb
<h1>Editing todo_list</h1>

<%= render 'form' %>

<%= link_to 'Show', @todo_list %> |
<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/index.html.erb
<h2>
  <%= link_to 'Listing todo_lists', todo_lists_path %>
</h2>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @todo_lists.each do |todo_list| %>
      <tr id='<%= dom_id(todo_list) %>'>
        <td><%= todo_list.title %></td>
        <td><%= todo_list.description %></td>
        <td>
          <%= link_to 'List Items', todo_list_todo_items_path(todo_list) %>
          <%= link_to 'Show', todo_list %>
          <%= link_to 'Edit', edit_todo_list_path(todo_list) %>
          <%= link_to 'Destroy', todo_list, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Todo list', new_todo_list_path %>

app/views/todo_lists/new.html.erb
<h1>New todo list</h1>

<%= render 'form' %>

<%= link_to 'Back', todo_lists_path %>

app/views/todo_lists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @todo_list.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @todo_list.description %>
</p>

<%= link_to 'Edit', edit_todo_list_path(@todo_list) %> |
<%= link_to 'Back', todo_lists_path %>